version: '3.8'

services:
  telegram_ai:
    image: tonylukin/telegram_ai:latest
    container_name: telegram_ai
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        alembic upgrade head &&
      "
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_ai
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
