"""add moodflow user reactions

Revision ID: 53e8f4406f11
Revises: 8ebda4843d2b
Create Date: 2026-01-22 23:34:15.373439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e8f4406f11'
down_revision: Union[str, None] = '8ebda4843d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add Telegram linkage columns for message lookup
    op.execute("""
    ALTER TABLE moodflow_chat_messages
      ADD COLUMN IF NOT EXISTS tg_message_id BIGINT NULL;
    """)

    # Raw reactions table
    op.execute("""
    CREATE TABLE IF NOT EXISTS moodflow_user_reactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL,
      chat_id BIGINT NOT NULL,
      tg_message_id BIGINT NOT NULL,

      reaction_value TEXT NOT NULL,     -- emoji char or custom_emoji_id or raw

      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    """)

    op.execute("""
    CREATE INDEX IF NOT EXISTS ix_moodflow_user_reactions_user_id
      ON moodflow_user_reactions(user_id);
    """)

    op.execute("""
    CREATE INDEX IF NOT EXISTS ix_moodflow_user_reactions_chat_id_tg_message_id
      ON moodflow_user_reactions(chat_id, tg_message_id);
    """)

def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS moodflow_user_reactions;")
    op.execute("""
    ALTER TABLE moodflow_chat_messages
      DROP COLUMN IF EXISTS tg_message_id;
    """)
