"""post reactions change bot id and post id

Revision ID: d13707c1e05b
Revises: 87bcf180ee6e
Create Date: 2025-11-08 17:20:03.246784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd13707c1e05b'
down_revision: Union[str, None] = '87bcf180ee6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE tg_post_reactions;')
    op.add_column('tg_post_reactions', sa.Column('reactions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tg_post_reactions', sa.Column('bot_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_constraint('uq_tg_post_reactions_post_id_channel_bot_id', 'tg_post_reactions', type_='unique')
    op.create_unique_constraint('uq_tg_post_reactions_post_id_channel', 'tg_post_reactions', ['post_id', 'channel'])
    op.drop_constraint('tg_post_reactions_bot_id_fkey', 'tg_post_reactions', type_='foreignkey')
    op.drop_column('tg_post_reactions', 'reaction')
    op.drop_column('tg_post_reactions', 'bot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_post_reactions', sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tg_post_reactions', sa.Column('reaction', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.create_foreign_key('tg_post_reactions_bot_id_fkey', 'tg_post_reactions', 'bots', ['bot_id'], ['id'])
    op.drop_constraint('uq_tg_post_reactions_post_id_channel', 'tg_post_reactions', type_='unique')
    op.create_unique_constraint('uq_tg_post_reactions_post_id_channel_bot_id', 'tg_post_reactions', ['post_id', 'channel', 'bot_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tg_post_reactions', 'bot_ids')
    op.drop_column('tg_post_reactions', 'reactions')
    # ### end Alembic commands ###
